apiVersion: v2
# appVersion: 0.1-4-2ad0c117
appVersion: latest
description: Helm Chart for deploying the Topl BTC Wallet.
name: btc-wallet
type: application
version: 0.1.0
icon: https://topl.co/wp-content/uploads/2023/06/topl_white_horiz.svg
home: https://topl.co
sources:
  - https://github.com/Topl/helm-charts
  - https://topl.github.io/helm-charts/
# dependencies:
#   - name: bitcoin-node
#     version: 0.1.0
#     # repository: https://topl.github.io/helm-charts/
#     repository: "file://../bitcoin-node"
#     condition: bitcoin-node.enabled
